# Pre-commit
# https://github.com/pre-commit/pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
      - id: no-commit-to-branch

  - repo: local
    hooks:
      - id: infracost_generate_config
        name: Infracost generate config
        entry: bash -c 'infracost generate config --repo-path=. --template-path=infracost.yml.tmpl --out-file=infracost.yml'
        language: system
        files: ^infracost\.yml\.tmpl$
        verbose: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt

      # To speed up local validation add the following to your ~/.zshrc:
      # export TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache

      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-upgrade

      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-exiting-file=true
          - --hook-config=--create-file-if-not-exist=false

      - id: infracost_breakdown
        args:
          - --args=--config-file=infracost.yml
          - --args=--sync-usage-file
